# labels auto assigned to PR, keep in sync with labels.yml
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["README.md", "*.md", "docs/**"]
markdown:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["docs/*.md", "*.md", "LICENSE",  ".github/pull_request_template.md"]
markdown:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["docs/**", "*.md", "LICENSE"]
dependencies:
  - any:
      - head-branch: ["^dependabot"]
just:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["Justfile"]
shell:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/*.sh", ".zshrc", "**/*.zsh"]
brew:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["Brewfile"]
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              [".github/workflows/*", ".github/actions/*"]
git_hooks:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["githooks/**"]
