name: "Code Quality"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  check-editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: EditorConfig Check
        uses: editorconfig-checker/action-editorconfig-checker@v2

  check-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Shell scripts
        uses: luizm/action-sh-checker@master
        with:
          sh_checker_exclude: ".zshrc"

  check-markdown-code-quality:
    name: Check Markdown Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Markdown format
        uses: DavidAnson/markdownlint-cli2-action@v16
