name: "Code Quality"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  check-editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: EditorConfig Check
        uses: editorconfig-checker/action-editorconfig-checker@v2

  check-code-format:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Code Format
        uses: creyD/prettier_action@v4.3
